name: flutter_web_dashboard
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: 2.0.10+1
  intl: 0.19.0
  fl_chart: 0.67.0
  syncfusion_flutter_charts: 25.1.37
  auto_route: 8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.2
  auto_route_generator: 8.0.0
  flutter_gen_runner: 5.4.0   

flutter_gen:
  output: lib/presentation/theme/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: ProjectAssets

  fonts:
    enabled: true
    outputs:
      class_name: ProjectFontFamily

  colors:
    enabled: false

flutter:
  uses-material-design: true

  assets: 
    - assets/icons/
  
  fonts:
    - family: MyriadPro
      fonts: 
        - asset: assets/fonts/MyriadPro/MyriadPro-Black.ttf
          weight: 900
        - asset: assets/fonts/MyriadPro/MyriadPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/MyriadPro/MyriadPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MyriadPro/MyriadPro-Regular.ttf
          weight: 400  
        - asset: assets/fonts/MyriadPro/MyriadPro-Light.ttf
          weight: 300
