name: flutter_web_dashboard
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0

  intl: ^0.17.0
  fl_chart: ^0.40.6
  syncfusion_flutter_charts: ^19.4.38
  auto_route: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.0    
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets: 
    - assets/icons/
  
  fonts:
    - family: MyriadPro
      fonts: 
        - asset: assets/fonts/MyriadPro/MyriadPro-Black.ttf
          weight: 900
        - asset: assets/fonts/MyriadPro/MyriadPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/MyriadPro/MyriadPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MyriadPro/MyriadPro-Regular.ttf
          weight: 400  
        - asset: assets/fonts/MyriadPro/MyriadPro-Light.ttf
          weight: 300
